### ISSUE TITLE
下载文件导致OOM

### ISSUE THREAD

**Issue by Khaos116** [Ayvytr/OKHttpLogInterceptor#4]
2021-01-30 12:47:03.947 27256-27331/com.abase.dev E/CrashReport: java.lang.OutOfMemoryError: Failed to allocate a 119703592 byte allocation with 25165824 free bytes and 65MB until OOM, target footprint 157875392, growth limit 201326592
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:125)
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:249)
        at okio.Buffer.readString(Buffer.kt:313)
        at okio.Buffer.readString(Buffer.kt:302)
        at com.ayvytr.okhttploginterceptor.ExtKt.bodyString(Ext.kt:80)
        at com.ayvytr.okhttploginterceptor.ExtKt.formatAsPossible(Ext.kt:90)
        at com.ayvytr.okhttploginterceptor.LoggingInterceptor.printResponse(LoggingInterceptor.kt:137)
        at com.ayvytr.okhttploginterceptor.LoggingInterceptor.logIntercept(LoggingInterceptor.kt:87)
        at com.ayvytr.okhttploginterceptor.LoggingInterceptor.intercept(LoggingInterceptor.kt:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

**Comment by Khaos116** [comment]
https://blog.csdn.net/sese12138/article/details/106019355/

https://blog.csdn.net/lerous/article/details/98039566

**Comment by Khaos116** [comment]
你看有没有办法处理一下文件下载或者太大的情况，如果不能处理，那就只能单独另外用一个OkHttpClient了

**Comment by Ayvytr** [comment]
问下，你这边是不是下载文件的时候设置有contentType，一般请求没有？

**Comment by Ayvytr** [comment]
你这边下载文件的时候有没有设置contentType？我看下加筛选条件

**Comment by Ayvytr** [comment]
新版3.0.5已发，已做限制

**Comment by Khaos116** [comment]
大佬牛逼

**Comment by Ayvytr** [comment]
没事，要是有问题就再提Issue
